USB_VID = 0x358D
USB_PID = 0x0101
USB_PRODUCT = "IB_DUAL"
USB_MANUFACTURER = "Interplan Co., Ltd."

CHIP_VARIANT = SAMD51G19A
CHIP_FAMILY = samd51

QSPI_FLASH_FILESYSTEM = 1
EXTERNAL_FLASH_DEVICES = GD25Q64C
LONGINT_IMPL = MPZ

# No I2S on SAMD51G
CIRCUITPY_AUDIOBUSIO = 0

# CIRCUITPY_BITBANG_APA102 = 1

#FROZEN_MPY_DIRS += $(TOP)/frozen/ib_dual/
